import useDocumentTitle from '../../hooks/useDocumentTitle';

import '../../index.css'


const PrivacyPolicy = () => {
    // >>>>>>>>>>>>>>>>> Change Document Title Dynamically
    useDocumentTitle('Privacy Policy - VoltCart');

    return (
        <>
            <div className="info_pages container_layout mx-auto flex justify-center items-center flex-col "  >

                <h1  >Privacy Policy</h1>

                <h2>VoltCart’s, Approach to Security:</h2>
                <p>VoltCart is committed to respect your privacy. VoltCart perceives high security standards to ensure its customers secure online transactions and to protect your sensitive information. Being the data controller VoltCart is responsible to secure your data and committed to practice advanced firewall technology for the order process. This privacy policy (” Privacy Policy”) together with Terms of Use governs the use of website <Link to='/'> www.voltcart.com </Link> (the “Website”) an ecommerce platform facilitating sale purchase of products to the users of the website. This Privacy Policy sets out the type of information collected from the users, including the nature of the Sensitive Personal Data or Information (defined hereinafter), the purpose, means and modes of usage of such information and how and to whom we shall disclose or transfer such information. You may at any time withdraw your consent for collection and use of your information including Personal Information (defined hereinafter) or Sensitive Personal Data or Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Personal Information based on your previous consent prior to the withdrawal. Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the website. If you have any queries about our privacy policy, please contact us at <a href="mailto:info.voltcartt@gmail.com">info.voltcartt@gmail.com</a> This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

                <h2>Cookies:</h2>
                <p>Cookies are unique identifiers that we transfer to your device to enable our systems to recognize your device. For enhanced shopping experience, VoltCart uses cookies to store your browsing information. Cookies do not save your PII (Personally Identifiable Information), though you can change the cookie settings as per your preferences. By using the website, we believe that you consent with the cookie policy.</p>

                <h2>User Consent:</h2>
                <p>When you access the website or fill in your details to buy the products or services offered at website, VoltCart will accept it as your consent with the privacy policy. For user who are not comfortable with the clause and conditions to share their personally identifiable information, it is requested to abort the use of the website.</p>

                <h2>Type of information we collect:</h2>

                <ul>
                    <li>We may collect your contact details, such as your name, email address, phone number, postal address and delivery address (if different).</li>
                    <li>We may require your banking details such as credit card number, card holder name, expiration date and CVV or other details necessary for internet banking.</li>
                    <li>In order to improve the shopping experience, we may seek order details of your previous purchases, including transactions and pricing details.</li>
                    <li>We may also collect your demographic information (gender, age, income) to conduct optional online surveys to asses our services.</li>
                    <li>We will collect your session and log in information, which include your IP address, operating system, browser type, browser language, date and time of request.</li>
                    <li>We will also collect sign in information for third party accounts shared on our website such as, Google, Facebook, Instagram, Twitter, Pinterest etc.</li>
                    <li>We shall ask for email communication by any user, for product inquiry, order and transaction details, for any complaints and disputes etc.</li>
                    <li>You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require deletion of your information partially or fully by logging into your account on the website.</li>
                </ul>

                <h2>How we use or share it:</h2>
                <p>We conduct the business in an ethical manner; hence we collect the personal information of our users or customer only to cater best products and services at <Link to='/'> www.voltcart.com </Link>. We do not sell, trade, share or transfer your information to any third parties.</p>

                <ul>
                    <li>Our affiliates and partners that are involved in buying and delivering process, shall use your information. In case of a merger or acquisitions, other business entities may use your information.</li>
                    <li>An aggregated form of information may be used to understand the consumer behavior so that we can improve the shopping experience. Our business and marketing activities may also use the demographical profiles of our users.</li>
                    <li>To tell you about deals, offers, new launches, shipment status, informational and promotional content, we will use your contact information.</li>
                    <li>Our cookie policy is used to customize your experience, we may use the information stored in your browser to let you see the recently viewed items, your wish list, cart features etc.</li>
                    <li>To understand the consumer behavior, buying preferences and to analyze how user interaction is being forwarded, we will use traffic flow and session login information.</li>
                    <li>User engagement and time spent by each user on our site accessed with the help your IP address and traffic source information. We may use it to measure the performance.</li>
                    <li>User information may be required in case of legal disputes, regulatory or statutory requirements, troubleshoot problems, collect fees owed, detect or protect against errors, prevent abuse of our services, prevent violation of rights of third parties, enforce our terms and conditions.</li>
                    <li>For internal analytical and research purposes such as auditing, data analysis and research to improve our products, services and customer communications.</li>

                </ul>

                <h2>Security:</h2>
                <p>VoltCart implements standard measures as required under applicable law, rules and regulations to protect against unauthorized access and interception of data. However, no internet site can fully eliminate security risks. VoltCart endeavors’ to take all measures to protect the security, integrity and confidentiality of the data against unauthorized breach and hacking. For the purpose of checking possible vulnerabilities and attacks, VoltCart may conduct periodical internal review of data and security measures on the platforms. However, the platforms cannot ensure or warrant a 100% security of the platforms. As part of the website’s security procedure, you are under obligation to treat ID, code, password as confidential. Notwithstanding anything contained in this policy or elsewhere, VoltCart shall not be held responsible for any loss, damage or misuse of the Data, if such loss, damage or misuse is attributable to a Force Majeure Event. A “Force Majeure Event” means any event that is beyond the reasonable control of VoltCart and includes, without limitation, fire, flood, explosion, civil commotion, strikes, lock outs or industrial action of any kind, riots, insurrection, war, acts of government, power failure, sabotage, computer hacking, unauthorized access to computer data and storage device, system failure, virus, attacks, bugs, computer crashes, breach of security and encryption.</p>

                <h2>Opt-Out Policy:</h2>
                <p>We also provide an opt-out option to our registered users to unsubscribe all the non-essential mails and communication from us and our partners. We reserve the right to limit membership based on availability of contact information. All users will be notified by email prior to any actions taken.</p>

                <h2>Retention of information:</h2>
                <p>We will retain your information and any data for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted under the applicable law.</p>

                <h2>Cookies Policy:</h2>
                <p>The VoltCart uses temporary cookies to store certain data. We do not store personal information in the cookies. Information collected by us, by any means whatsoever, that does not personally identify the User as an individual (such as patterns of utilization described above) is exclusively owned by us and may be used by us and third-party service providers for technical administration of the Platforms, user administration, research, development, and other purposes. Adjusting your web browser settings to decline cookies might prevent you from accessing certain features of our website. We collaborate with other companies and entities to deliver advertisements. These include third-party ad servers, ad agencies, technology vendors, and research firms. While we may tailor ads based on general profiles, we don’t use personal information for ad targeting. During ad delivery or service optimization, we may allow authorized third parties to place or recognize a unique cookie on the User’s browser. We don’t have control over third-party websites displayed as search results or links on the website. These sites may place their own cookies or files on users’ computers, collect data, and request personal information. We’re not responsible for their actions, privacy practices, or content quality. Inclusion or exclusion doesn’t imply any endorsement by us of such websites. We may retain call records from and to users for the purpose of service administration, research, training, business development, and user management. When necessary, by law or to facilitate services, we may share these records with third parties. By using our services, you grant us permission to reproduce and publish any testimonials or reviews you provide on the website. We may edit or paraphrase these testimonials for publication.</p>

                <h2>Amendment to Policy:</h2>
                <p>We reserve the right to amend this Privacy Policy at any time. The Privacy Policy, as and when modified, shall be updated on the VoltCart Website. We encourage you to review this Privacy Policy whenever you visit our website to understand how your personal information is used.</p>

                <h2>Severability:</h2>
                <p>In the event any provision of this Policy (or part of any provision) is invalid, illegal or unenforceable, such provision shall be ineffective only to the extent of such prohibition or invalidity and such provision be deemed to be deleted, and the validity and enforceability of the other provisions of this Policy will not be affected.</p>
            </div>
        </>
    )
}

export default PrivacyPolicy;
